#!/bin/sh
set -o errexit

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 WIFI_SSID WIFI_KEY" >&2
  exit 1
fi

WIFI_SSID="$1"
WIFI_KEY="$2"

uci set system.@system[0].hostname="wrt"
uci set system.@system[0].zonename="Europe/Zurich"

# LAN
uci set network.lan.ipaddr=172.16.0.1

# WIRELESS

# https://openwrt.org/toh/linksys/wrt3200acm#wifi_driver_bug_and_workaround
opkg remove kmod-mwifiex-sdio

wifi config > /etc/config/wireless

# 5 GHz
uci set wireless.radio0.disabled="0"
uci set wireless.radio0.country="CH"
uci set wireless.radio0.cell_density="0"
uci set wireless.default_radio0.ssid="${WIFI_SSID}"
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key="$WIFI_KEY"

# 2.4 GHz
uci set wireless.radio1.disabled="0"
uci set wireless.radio1.country="CH"
uci set wireless.radio1.cell_density="0"
uci set wireless.default_radio1.ssid="${WIFI_SSID}"
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key="$WIFI_KEY"

# Local domain
uci set dhcp.@dnsmasq[0].domain='thewagner.home'
uci set dhcp.@dnsmasq[0].local='/thewagner.home/'

# CNAME records
while uci -q get dhcp.@cname[0]; do
    uci delete dhcp.@cname[0]
done

uci add dhcp cname
uci set dhcp.@cname[-1].cname="alertmanager.thewagner.home"
uci set dhcp.@cname[-1].target="nuc.thewagner.home"

uci add dhcp cname
uci set dhcp.@cname[-1].cname="git.thewagner.home"
uci set dhcp.@cname[-1].target="nuc.thewagner.home"

uci add dhcp cname
uci set dhcp.@cname[-1].cname="hydra.thewagner.home"
uci set dhcp.@cname[-1].target="nuc.thewagner.home"

uci add dhcp cname
uci set dhcp.@cname[-1].cname="loki.thewagner.home"
uci set dhcp.@cname[-1].target="nuc.thewagner.home"

uci add dhcp cname
uci set dhcp.@cname[-1].cname="metrics.thewagner.home"
uci set dhcp.@cname[-1].target="nuc.thewagner.home"

uci add dhcp cname
uci set dhcp.@cname[-1].cname="prometheus.thewagner.home"
uci set dhcp.@cname[-1].target="nuc.thewagner.home"

uci add dhcp cname
uci set dhcp.@cname[-1].cname="tv.thewagner.home"
uci set dhcp.@cname[-1].target="nuc.thewagner.home"

uci add dhcp cname
uci set dhcp.@cname[-1].cname="mqtt.thewagner.home"
uci set dhcp.@cname[-1].target="nuc.thewagner.home"

# Node exporter
opkg install \
    libubus-lua \
    prometheus-node-exporter-lua \
    prometheus-node-exporter-lua-nat_traffic \
    prometheus-node-exporter-lua-netstat \
    prometheus-node-exporter-lua-openwrt \
    prometheus-node-exporter-lua-wifi \
    prometheus-node-exporter-lua-wifi_stations
uci set prometheus-node-exporter-lua.main.listen_interface='*'

# Tailscale
opkg install iptables tailscale

CHANGES=$(uci changes)
if [ -n "$CHANGES" ]; then
    echo "Changes:"
    uci changes
    echo ""
    echo ""
    echo "This script doesn't restart any services. You may need to run:"
    echo "- wifi"
    echo "- service network restart"
    echo "- service dnsmasq restart"
    echo ""
    echo "Or just reboot the device"
else
    echo "No changes. Configuration is up-to-date!"
fi

uci commit
